# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: bb
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    darwin: macOS
