# .goreleaser.yml

builds:
  - main: main.go
    binary: bb
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format: tar.gz
  replacements:
    darwin: macOS

brew:
  github:
    owner: tolitius
    name: bb8
  folder: Formula
  homepage: "https://github.com/tolitius/bb8"
  description: "a command line interface to Stellar networks"
  install: |
    bin.install "bb"
